AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition and a Lambda function.



Parameters:

    ###################################################################################
    ##                            Parameters For Lambda                              ##
    ###################################################################################
    
    LambdaLayerName:
        Type: String
        Default: lksn-restapi-layer
        Description: The name of the Lambda layer
    
    LambdaAPIGatewayStageName:
        Type: String
        Default: prod
        Description: The stage name of the API Gateway
        AllowedValues:
        - prod
        - dev
        - test
        - staging

    LambdaS3Bucket:
        Type: String
        Default: lksncc-2025-s3-bucket
        Description: The name s3 bucket for source code lambda layer
    
    LambdaLayerS3Key:
        Type: String
        Default: layer.zip
        Description: The name s3 key for source code lambda layer
    
    LambdaRuntime:
        Type: String
        Default: nodejs22.x
        Description: The runtime of the Lambda function
        AllowedValues:
        - nodejs22.x
        - nodejs20.x
        - nodejs18.x
    
    
    LambdaBaseFunctionName:
        Type: String
        Default: lksn-restapi
        Description: The name of the Lambda function
    
    LambdaArchitecture:
        Type: String
        Default: x86_64
        Description: The architecture of the Lambda function
        AllowedValues:
        - x86_64
        - arm64
    
    LambdaFunctionS3KeyMethodGET:
        Type: String


Resources:

    ###################################################################################
    ##                            Resources For Lambda                               ##
    ###################################################################################

    LambdaLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: !Ref LambdaLayerName
            Description: The layer for the Lambda function
            ContentUri:
                Bucket: !Ref LambdaS3Bucket
                Key: !Ref LambdaLayerS3Key
            CompatibleRuntimes:
                - !Ref LambdaRuntime
            LicenseInfo: MIT
    
    LambdaAPIGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref LambdaAPIGatewayStageName
            EndpointConfiguration: REGIONAL

    LambdaFunctionMethodGET:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub "${LambdaBaseFunctionName}-method-get"
            Handler: !Ref LambdaFunctionMethodGETHandler
            Runtime: !Ref LambdaRuntime
            Architectures:
                - !Ref LambdaArchitecture
            MemorySize: !Ref LambdaFunctionMemory
            CodeUri:
                Bucket: !Ref LambdaS3Bucket
                Key: !Ref LambdaFunctionS3KeyMethodGET
            Layers:
                - !Ref LambdaLayer